version: '3.11'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbit"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "123"
    ports:
      - "5672:5672"
      - "15672:15672"